More examples are moved to examples directory.
vaguecoder/gorilla-mux pull request #15
Opened 2023-01-06 14:40 UTC by Rishav1707

## This PR closes the following issue:
closes #14 

## Changes made:
- More examples are moved to the `examples/` directory.

2023-01-06 16:01 UTC, tanryberdi commented
Hey @Rishav1707 , could you please add `Signed-off-by: Random J Developer <random@developer.example.org>` to end of your commit message

2023-01-06 16:04 UTC, tanryberdi commented
> > Hey @Rishav1707 , could you please add `Signed-off-by: Random J Developer <random@developer.example.org>` to end of your commit message
> 
> But, how?

you can use `git commit --amend` to edit your commit message

2023-01-06 16:55 UTC, Rishav1707 commented
> Hey @Rishav1707 , could you please add `Signed-off-by: Random J Developer <random@developer.example.org>` to end of your commit message

Done @tanryberdi

2023-01-06 18:29 UTC, vaguecoder commented
> > Hey @Rishav1707 , could you please add `Signed-off-by: Random J Developer <random@developer.example.org>` to end of your commit message
> 
> But, how?

Details of DCO are missing as #11 is still not in place. You need to add your name and email to git and use `git commit -s ...` while committing changes. Please refer to [this][1].

[1]: https://docs.pi-hole.net/guides/github/how-to-signoff/

2023-01-06 18:32 UTC, vaguecoder commented on README.md
> +And this is all you need to know about the basic usage. More advanced options are explained in [examples](./examples/examples.md).
Not required. Hyperlinks from the following section in `README.md` should be linked to respective documents in examples.

```

* [Install](#install)
* [Examples](#examples)
* [Matching Routes](#matching-routes)
* [Static Files](#static-files)
* [Serving Single Page Applications](#serving-single-page-applications) (e.g. React, Vue, Ember.js, etc.)
* [Registered URLs](#registered-urls)
* [Walking Routes](#walking-routes)
* [Graceful Shutdown](#graceful-shutdown)
* [Middleware](#middleware)
* [Handling CORS Requests](#handling-cors-requests)
* [Testing Handlers](#testing-handlers)
* [Full Example](#full-example)
```

2023-01-06 18:36 UTC, vaguecoder commented
@Rishav1707 As mentioned in #14, we need one sheet for each topic.
Say, [Matching Routes](https://github.com/vaguecoder/gorilla-mux#matching-routes) will be in `matching-routes.md`

2023-01-07 13:53 UTC, Rishav1707 commented
> @Rishav1707 As mentioned in #14, we need one sheet for each topic. Say, [Matching Routes](https://github.com/vaguecoder/gorilla-mux#matching-routes) will be in `matching-routes.md`

Done @vaguecoder

2023-01-07 15:12 UTC, vaguecoder commented on README.md
> +And this is all you need to know about the basic usage. More advanced options are explained in [examples](./examples/).
Calling topics like static files, mw, etc. advanced topics is an overstatement. Let's remove this last line as hyperlinks are already in place. Rest all looks good.

2023-01-07 15:17 UTC, vaguecoder commented
> > > Hey @Rishav1707 , could you please add `Signed-off-by: Random J Developer <random@developer.example.org>` to end of your commit message
> > 
> > 
> > But, how?
> 
> Details of DCO are missing as #11 is still not in place. You need to add your name and email to git and use `git commit -s ...` while committing changes. Please refer to [this](https://docs.pi-hole.net/guides/github/how-to-signoff/).

@Rishav1707 The DCO needs to be signed on all commits. Please squash all of your commits together using [ref.][1] and sign your commits using `-s` as we previously discussed. Ask in [discussion][2] section if you find it hard to follow.

Rest all looks good :thumbsup:

[1]: https://stackoverflow.com/a/5201642
[2]: https://github.com/vaguecoder/gorilla-mux/discussions/23

2023-01-07 18:21 UTC, vaguecoder commented
As an extra commit was squashed together, there are conflicts. Please try as [discussed][1] and let us only post here once that is resolved.

[1]: https://github.com/vaguecoder/gorilla-mux/discussions/23#discussioncomment-4621393

2023-01-07 18:22 UTC, vaguecoder requested changes
Hold until squash is fixed.

2023-01-08 07:53 UTC, Rishav1707 commented
I am just closing this issue and committing another PR because it just messed up with different things

2023-01-08 07:53 UTC, closed without merging